### ISSUE TITLE
Add nmbs_read_single_register

### ISSUE THREAD

**Issue by eNovware** [debevv/nanoMODBUS#42]
it should be nice to include a nmbs_read_single_register, exactly like nmbs_write_single_register.
thanks.

**Comment by debevv** [comment]
Hi, `nmbs_read_single_register` does not exist because the API is meant to reflect 1:1 the function codes found in the official [modbus spec](https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf). The spec effectively presents a bit of asymmetry between the read/write FCs, but I prefer the API to be coherent, at least for the "core" ones.

**Comment by eNovware** [comment]
OK, got it.
Thanks for the answer.
Thanks for this library.
